title: 'Welcome'
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: ""
baseurl: ""
paginate_path: "posts/page:num/"
permalink: posts/:slug/

markdown: redcarpet
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /
 - title: Projects
   url: http://madeby.martn.st
 - title: Blog
   url: http://blog.martn.st


social:
   github: martnst
   twitter: martn_st
   # facebook: 
   email: hi@martn.st 

# google_analytics: "UA-58263416-1"
