title: '&lt;blog/&gt;'
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: ""
baseurl: ""
paginate_path: "posts/page:num/"
permalink: posts/:slug/

markdown: redcarpet
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /
 - title: About
   url: /about
 # - title: Contact
   # url: /contact

social:
   github: martnst
   twitter: martn_st
   # facebook: 
   email: hi@martn.st 

google_analytics: "UA-68457603-4"

# ExternalLinks plugin:
remoteUrl: martn.st
localUrl: localhost:4000
